# Site settings
title: GSA Digital Service Slides
email: sara.cope@gsa.gov

description: > # this means to ignore newlines until "baseurl:"
  Slide decks for GSA Digital Service!

baseurl: "/slides"
url:

# Build settings
collections:
  slides:
    output: true
    permalink: "/:path/"
